export var BEAT_PAWN = "BEAT_PAWN";
export var UNABLE_TO_MOVE = "UNABLE_TO_MOVE";
export var ADD_ACTION = "ADD_ACTION";
export var MOVE_FORWARD = "MOVE_FORWARD";
export const THROW_DICE = "THROW_DICE";
export const LEAVE_BASE = "LEAVE_BASE";
export const RED_LEAVE_BASE = "RED_LEAVE_BASE";
export const BLUE_LEAVE_BASE = "BLUE_LEAVE_BASE";
export const YELLOW_LEAVE_BASE = "YELLOW_LEAVE_BASE";
export const GREEN_LEAVE_BASE = "GREEN_LEAVE_BASE";
export const NEXT_PLAYER="NEXT_PLAYER";
export const CLEAN_AFTER_MOVE_FORWARD ="CLEAN_AFTER_MOVE_FORWARD";
export const BACK_TO_HOME = "BACK_TO_HOME";
//Player
export const ADD_LEAVE_BASE_ACTION = "ADD_LEAVE_BASE_ACTION";