export const RED_LEAVE_BASE="RED_LEAVE_BASE";
export const RED_ADD_TO_BOARD_FROM_BASE="RED_ADD_TO_BOARD_FROM_BASE";
export const BLUE_LEAVE_BASE="BLUE_LEAVE_BASE";
export const YELLLOW_LEAVE_BASE="YELLLOW_LEAVE_BASE";
export const GREEN_LEAVE_BASE="GREEN_LEAVE_BASE";
export const ADD_ACTION="ADD_AUCTION";